<?php

/**
 * This module provides a simple way to execute jobs external to Drupal
 * by leveraging the power of the webform module.
 */

/**
 * Implements hook_menu().
 */
function job_menu() {
  $items = array();

  return $items;
}

function job_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'job_node_form') {
    # available weform fields
    $available_webform_fields = array();
    $found_results_field=0;
    foreach ($form['webform']['#value']['components'] as $component) {
      if ($component['form_key']=='results') { continue; }
      $available_webform_fields[] = '%'.$component['form_key'];
    }
    $form['field_job_command']['und'][0]['value']['#description'] = t('The following Webform fields are available for substitution: %fields', array('%fields' => join(', ', $available_webform_fields)));
  }
}

function job_webform_submission_presave($node, &$submission) {
  if (0) {  # XXX validate job here!
    $job_results = 'Error validating job';
  }
  $mapping = _job_webform_component_mapping($node);
  # XXX schedule job here!
  $job_results = 'Scheduled for execution';
  $job_type = $node->field_job_type['und'][0]['value'];
  $job_cmd = $node->field_job_command['und'][0]['value'];
  foreach (array_keys($mapping) as $fieldname) {
      $argdata = $submission->data[$mapping[$fieldname]]['value'][0];
      $job_cmd = preg_replace('/%'.$fieldname.'/', $argdata, $job_cmd);
  }
  if (strcmp($job_type, 'shell')==0) {
    $job_output = `$job_cmd`;
    $job_results = 'Successful shell job: '.$job_output;
  } else if (strcmp($job_type, 'php')==0) {
    unset($job_output);
    eval($job_cmd);
    if (isset($job_output)) { 
      $job_results = 'Successful PHP job: '.$job_output;
    } else {
      $job_output = false;
      $job_results = 'Error executing php job: $job_output not set';
    }
  } else {
    $job_results = 'Error scheduling job: unknown job type';
  }
  $job_results .= "\nCommand: ".$job_cmd;
  watchdog('job', $job_results);
  $submission->data[$mapping['results']] = array( 'value' => array( 0 => $job_results));
}

function job_webform_submission_actions($node, $submission) {
  if (webform_results_access($node)) {
    $actions['myaction'] = array(
      'title' => t('Do my action'),
      'href' => 'node/' . $node->nid . '/submission/' . $submission->sid . '/myaction',
      'query' => drupal_get_destination(),
    );
  }
  return $actions;
}

function job_webform_submission_load(&$submissions) {
  foreach ($submissions as $sid => $submission) {
    $submissions[$sid]->new_property = 'fruit';
  }
}

function job_webform_submission_render_alter(&$renderable) {
  # dd($renderable);
}

function _job_webform_component_mapping($node) {
  $mapping = array();
  $components = $node->webform['components'];
  foreach ($components as $i => $component) {
    $key = $component['form_key'];
    $mapping[$key] = $i;
  }
  return $mapping;
}

